// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MyImage;
//
//    var sampleImageJson = SampleImageJson.FromJson(jsonString);

namespace MyImage
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SampleImageJson
    {
        [JsonProperty("item_name", NullValueHandling = NullValueHandling.Ignore)]
        public string ItemName { get; set; }

        [JsonProperty("item_url", NullValueHandling = NullValueHandling.Ignore)]
        public string[] ItemUrl { get; set; }
    }

    public partial class SampleImageJson
    {
        public static SampleImageJson FromJson(string json) => JsonConvert.DeserializeObject<SampleImageJson>(json, MyImage.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this SampleImageJson self) => JsonConvert.SerializeObject(self, MyImage.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
